// Generated by `cargo test -p blirp-core export_bindings` from crates/blirp-core/src/model.rs.
// Do not edit by hand.

export type JsonValue = number | string | boolean | Array<JsonValue> | { [key in string]: JsonValue } | null;

export type MachineRole = "standalone" | "node" | "hub";

export type SessionStatus = "starting" | "working" | "idle" | "waiting" | "completed" | "failed" | "detached";

export type SessionOrigin = "blirp" | "external";

export type EventKind = "user" | "assistant" | "tool_call" | "tool_result" | "system" | "file_edit" | "summary";

export type RecordKind = "decision" | "plan" | "note" | "open_thread" | "gotcha";

export type RecordStatus = "active" | "resolved" | "archived";

export type SuggestionTarget = "brief" | "record" | "wiki";

export type SuggestionStatus = "pending" | "accepted" | "rejected" | "dismissed";

export type ResourceKind = "link" | "repo" | "pr" | "issue" | "doc" | "file";

export type DeviceKind = "machine" | "browser";

export type FileKind = "file" | "dir" | "symlink" | "other";

export type SearchHitKind = "event" | "record";

export type MemoryPart = "brief" | "records" | "wiki" | "resources" | "suggestions";

export type IntegrationState = "installed" | "not_installed" | "unsupported";

export type InjectMode = "hook" | "instructions" | "flag" | "none";

export type CloneState = "running" | "done" | "failed";

export type Machine = { id: string, name: string, os: string, role: MachineRole, last_seen: number, revoked: boolean, };

/**
 * `GET /api/machines`: the replicated row plus runtime presence. `online`:
 * the machine has a live sync connection to the hub (as the hub reports
 * it), always true for this machine, null when unknown (standalone, not
 * connected to the hub, or a hub that does not report presence). With
 * presence known, `last_seen` is its connect, disconnect or latest minute
 * online (never replicated).
 */
export type MachineInfo = { online: boolean | null, id: string, name: string, os: string, role: MachineRole, last_seen: number, revoked: boolean, };

export type Project = { id: string, name: string, created_at: number, updated_at: number, deleted: boolean, 
/**
 * A machine's Chats bucket (§5, id `chats-<machine id>`): sessions that
 * belong to no project. Not listed among projects; its memory is never
 * injected. Absent in rows from blirp 0.1.0.
 */
chats: boolean, 
/**
 * Set on a deleted project that was merged into another one.
 */
merged_into: string | null, };

export type ProjectPath = { project_id: string, machine_id: string, path: string, 
/**
 * Normalized `host/owner/repo`, null when the folder is not a git repo or has no remote.
 */
git_remote: string | null, };

export type Session = { id: string, project_id: string, machine_id: string, 
/**
 * `claude|codex|opencode|pi|gemini|cursor|amp|aider|dsh|shell|custom:<name>`
 */
agent: string, 
/**
 * The agent's own session id (claude uuid, codex rollout uuid, ...).
 */
agent_session_id: string | null, origin: SessionOrigin, cwd: string, title: string | null, status: SessionStatus, branch: string | null, worktree: string | null, transcript_path: string | null, started_at: number, ended_at: number | null, last_activity_at: number, exit_code: number | null, 
/**
 * Distill output (§9), null until the session is distilled.
 */
summary: JsonValue | null, distilled_through_seq: number, tokens_in: number, tokens_out: number, cost_usd: number, parent_session_id: string | null, 
/**
 * Ended by a user Stop: `status` is `completed` and `exit_code` null.
 */
stopped_by_user: boolean, };

export type Event = { session_id: string, seq: number, ts: number, kind: EventKind, 
/**
 * Redacted, human-readable text.
 */
text: string, meta: JsonValue | null, };

export type Record = { id: string, project_id: string, kind: RecordKind, title: string, body: string, status: RecordStatus, pinned: boolean, source_session_id: string | null, created_at: number, updated_at: number, 
/**
 * `user`, `distiller` or a machine id.
 */
updated_by: string, };

/**
 * A project brief; also used for entries of the brief history.
 */
export type Brief = { 
/**
 * Id of this version's `brief_history` row: a UUIDv7, unique across
 * machines, so versions written concurrently on two machines never
 * overwrite each other. Empty in changes from older blirp versions.
 */
id: string, project_id: string, body_md: string, 
/**
 * Position in the project's history (1 = oldest, by time), derived
 * when read; for display and revert only.
 */
version: number, updated_at: number, updated_by: string, 
/**
 * Machine that wrote this version (empty when unknown).
 */
machine_id: string, };

export type WikiPage = { id: string, project_id: string, slug: string, title: string, body_md: string, updated_at: number, updated_by: string, deleted: boolean, };

export type Suggestion = { id: string, project_id: string, target: SuggestionTarget, 
/**
 * Record id or wiki slug being changed; null for the brief or for new items.
 */
target_id: string | null, 
/**
 * `BriefProposal`, `RecordProposal` or `WikiProposal` depending on `target`.
 */
proposal: JsonValue, rationale: string, source_session_id: string | null, status: SuggestionStatus, created_at: number, decided_at: number | null, };

export type BriefProposal = { body_md: string, };

export type RecordProposal = { kind: RecordKind, title: string, body: string, status: RecordStatus | null, };

export type WikiProposal = { slug: string, title: string, body_md: string, };

export type Resource = { id: string, project_id: string, kind: ResourceKind, url: string, title: string, meta: JsonValue | null, created_at: number, 
/**
 * Last change; replicated copies converge on the newest (§10). Changes
 * queued by versions without it (before migration 8) read as 0.
 */
updated_at: number, deleted: boolean, };

export type Device = { id: string, name: string, kind: DeviceKind, node_id: string | null, created_at: number, last_seen: number, revoked: boolean, can_control_terminals: boolean, };

export type ErrorBody = { error: ErrorDetail, };

export type ErrorDetail = { 
/**
 * Stable machine-readable code, e.g. `not_found`, `invalid_request`, `not_git`.
 */
code: string, message: string, };

export type Health = { version: string, machine: Machine, role: MachineRole, 
/**
 * What the calling client may do here.
 */
capabilities: Capabilities, 
/**
 * This machine is holding a sleep-prevention assertion because sessions
 * are live (`sessions.keep_awake`).
 */
keep_awake: boolean, };

/**
 * `GET /api/update`: whether a newer release than the daemon exists.
 */
export type UpdateStatus = { 
/**
 * This daemon's version.
 */
current: string, 
/**
 * Newest published release; null when checks are off or failed.
 */
latest: string | null, available: boolean, 
/**
 * Release notes of `latest`.
 */
notes_url: string | null, 
/**
 * `[update] check` in config.toml.
 */
enabled: boolean, 
/**
 * `blirp update` can replace this daemon's binary: the install script
 * installed it (its receipt matches), or it is the sidecar of the
 * desktop app the script installed. False for installers, package
 * managers and source builds, which update the way they were installed.
 */
self_update: boolean, 
/**
 * When GitHub was last asked (unix ms); null before the first check.
 */
checked_at: number | null, 
/**
 * Why that check failed (offline, rate limited, ...); null when it worked.
 */
error: string | null, 
/**
 * The last `blirp update` that tried to install a release on this
 * machine (from the Update now button or a terminal).
 */
last_update: UpdateOutcome | null, };

/**
 * One run of `blirp update` (not `--check`), a line of `logs/update.log`.
 */
export type UpdateOutcome = { 
/**
 * The version that ran the update.
 */
from: string, 
/**
 * The release it aimed for; null when it failed before finding one.
 */
to: string | null, 
/**
 * The files were replaced: `to` is installed now.
 */
installed: boolean, 
/**
 * Everything worked, including "nothing to install".
 */
ok: boolean, 
/**
 * Why it failed: before `installed`, `from` is still installed;
 * after it, the daemon did not start again.
 */
error: string | null, 
/**
 * Unix ms.
 */
finished_at: number, };

export type ProjectPathInfo = { machine_id: string, path: string, git_remote: string | null, 
/**
 * Folder is inside a git work tree (only known for this machine's paths).
 */
is_git: boolean, 
/**
 * Path belongs to the machine serving this response.
 */
local: boolean, };

export type ProjectSummary = { paths: Array<ProjectPathInfo>, is_git: boolean, 
/**
 * This machine's Chats bucket (sessions that belong to no project).
 */
is_home: boolean, 
/**
 * Project without folders: this machine's blirp workspace
 * (`BLIRP_HOME/workspaces/<id>`), where its sessions start. Set when the
 * project has no folder on any machine; the folder may not exist yet.
 */
workspace: string | null, session_count: number, live_session_count: number, last_activity_at: number | null, id: string, name: string, created_at: number, updated_at: number, deleted: boolean, 
/**
 * A machine's Chats bucket (§5, id `chats-<machine id>`): sessions that
 * belong to no project. Not listed among projects; its memory is never
 * injected. Absent in rows from blirp 0.1.0.
 */
chats: boolean, 
/**
 * Set on a deleted project that was merged into another one.
 */
merged_into: string | null, };

export type CreateProject = { 
/**
 * Folder to register (absolute, on this machine). Without it the
 * project has no folder and `name` is required.
 */
path?: string, name?: string, 
/**
 * Initial project brief (markdown).
 */
brief?: string, };

export type PatchProject = { name: string, };

export type MergeProject = { 
/**
 * Project that receives this project's paths, sessions and memory.
 */
into: string, };

/**
 * `POST /api/projects/:id/folders/remove`: unregister one of this
 * machine's folders. The project stays, also without any folder.
 */
export type RemoveProjectFolder = { path: string, };

/**
 * `POST /api/sessions/:id/move`.
 */
export type MoveSession = { 
/**
 * Target project; null moves the session to Chats.
 */
project_id: string | null, };

export type ProjectMemory = { brief: Brief | null, 
/**
 * Active records, pinned first then most recently updated.
 */
records: Array<Record>, recent_sessions: Array<Session>, };

export type PutBrief = { body_md: string, };

export type RevertBrief = { 
/**
 * History entry to restore, by its `version` number...
 */
version?: number, 
/**
 * ...or by its id (preferred: numbers can shift when versions written
 * earlier on another machine arrive).
 */
id?: string, };

export type CreateRecord = { kind: RecordKind, title: string, body: string, status?: RecordStatus, pinned?: boolean, };

export type PatchRecord = { kind?: RecordKind, title?: string, body?: string, status?: RecordStatus, pinned?: boolean, };

export type CreateWikiPage = { 
/**
 * `[a-z0-9-]`, 1-100 chars, unique per project.
 */
slug: string, title: string, body_md: string, };

export type PutWikiPage = { title: string, body_md: string, };

export type CreateResource = { kind: ResourceKind, url: string, title: string, meta?: JsonValue, };

export type PatchResource = { kind?: ResourceKind, url?: string, title?: string, meta?: JsonValue, };

export type GitStatusEntry = { 
/**
 * Path relative to the repo root, `/`-separated.
 */
path: string, 
/**
 * Source path of a rename or copy.
 */
orig_path: string | null, 
/**
 * Porcelain v2 index (staged) status letter, `.` when unchanged, `?` untracked.
 */
index: string, 
/**
 * Porcelain v2 work tree status letter, `.` when unchanged, `?` untracked.
 */
worktree: string, conflicted: boolean, };

export type GitStatus = { is_git: boolean, root: string, 
/**
 * Branch name, null when HEAD is detached.
 */
branch: string | null, 
/**
 * HEAD commit id, null before the first commit.
 */
head: string | null, upstream: string | null, ahead: number, behind: number, entries: Array<GitStatusEntry>, };

export type GitDiff = { path: string | null, 
/**
 * Unified diff against HEAD (staged + unstaged).
 */
diff: string, 
/**
 * Diff exceeded 1 MiB and was cut.
 */
truncated: boolean, };

export type FileEntry = { name: string, 
/**
 * Path relative to the listing root, `/`-separated.
 */
path: string, kind: FileKind, size: number, modified_at: number | null, };

export type DirListing = { 
/**
 * Absolute project root the listing is relative to.
 */
root: string, path: string, 
/**
 * Directories first, then files, each sorted by name.
 */
entries: Array<FileEntry>, };

export type FileContent = { root: string, path: string, size: number, 
/**
 * UTF-8 text; binary files and files over 1 MiB are rejected.
 */
content: string, };

export type SessionsPage = { items: Array<Session>, 
/**
 * Pass as `cursor` to fetch the next page; null on the last page.
 */
next_cursor: string | null, };

/**
 * `GET /api/sessions/:id`: the session plus how many subagent sessions
 * ingest recorded under it (origin `external` with `parent_session_id`
 * set to it, §8); list them with `GET /api/sessions?parent=<id>`.
 */
export type SessionDetail = { children_count: number, id: string, project_id: string, machine_id: string, 
/**
 * `claude|codex|opencode|pi|gemini|cursor|amp|aider|dsh|shell|custom:<name>`
 */
agent: string, 
/**
 * The agent's own session id (claude uuid, codex rollout uuid, ...).
 */
agent_session_id: string | null, origin: SessionOrigin, cwd: string, title: string | null, status: SessionStatus, branch: string | null, worktree: string | null, transcript_path: string | null, started_at: number, ended_at: number | null, last_activity_at: number, exit_code: number | null, 
/**
 * Distill output (§9), null until the session is distilled.
 */
summary: JsonValue | null, distilled_through_seq: number, tokens_in: number, tokens_out: number, cost_usd: number, parent_session_id: string | null, 
/**
 * Ended by a user Stop: `status` is `completed` and `exit_code` null.
 */
stopped_by_user: boolean, };

export type LaunchSession = { 
/**
 * Launch in this project's folder on this machine (a project without
 * folders: its blirp workspace). One of `project_id`/`cwd` is required.
 */
project_id?: string, 
/**
 * Launch in this folder; the project is resolved (and created) from it.
 * With `project_id` it must be inside one of the project's folders here,
 * or `add_folder` is set.
 */
cwd?: string, 
/**
 * With `project_id` and a `cwd` outside its folders: register `cwd` (its
 * git top level inside a repository) as a folder of the project first.
 */
add_folder?: boolean, 
/**
 * Agent id, e.g. `claude` or `custom:<name>`.
 */
agent: string, 
/**
 * Typed into the agent once its output settles, followed by Enter.
 */
prompt?: string, 
/**
 * Create a git worktree for the session (git projects only).
 */
worktree?: boolean, 
/**
 * Start with a handoff pack of this session (continue in / fork, §9).
 * Defaults the folder to the source session's folder.
 */
continue_from?: string, 
/**
 * Target machine id; defaults to this machine.
 */
machine?: string, cols?: number, rows?: number, };

export type PatchSession = { 
/**
 * New title; null clears it.
 */
title: string | null, };

/**
 * `POST /api/sessions/:id/worktree/remove`.
 */
export type RemoveWorktree = { 
/**
 * Also discard uncommitted changes and untracked files.
 */
force?: boolean, };

/**
 * Where `POST /api/sessions/:id/open` shows the session folder.
 */
export type OpenTarget = "folder" | "editor";

export type OpenSession = { target: OpenTarget, };

/**
 * `POST /api/sessions/:id/uploads`: a file pasted or dropped into the
 * session's terminal, saved on the machine that runs the session.
 */
export type UploadedFile = { 
/**
 * Absolute path on that machine.
 */
path: string, 
/**
 * `path` as a terminal drop would type it on that machine: in double
 * quotes on Windows, with backslash escapes elsewhere, unchanged when
 * it needs neither.
 */
quoted: string, 
/**
 * Bytes stored.
 */
size: number, };

export type EventsPage = { items: Array<Event>, 
/**
 * Pass as `after` to fetch the next page; null on the last page.
 */
next_after: number | null, };

export type SearchHit = { kind: SearchHitKind, project_id: string, session_id: string | null, seq: number | null, record_id: string | null, 
/**
 * Record title or session title.
 */
title: string | null, agent: string | null, 
/**
 * Plain text excerpt. Matched terms are wrapped in U+0002 (start) and
 * U+0003 (end); render them as highlights and escape everything else.
 */
snippet: string, ts: number, 
/**
 * bm25 rank; lower is better.
 */
score: number, };

export type SearchResults = { hits: Array<SearchHit>, };

export type AgentInfo = { 
/**
 * Launch id: built-in id or `custom:<name>`.
 */
id: string, display_name: string, builtin: boolean, installed: boolean, 
/**
 * Resolved executable.
 */
path: string | null, 
/**
 * First line of `--version` output.
 */
version: string | null, 
/**
 * Resume by the agent's own session id is supported.
 */
can_resume: boolean, integration: AgentIntegration, 
/**
 * Whether the agent is logged in for this machine's daemon, where that
 * can be checked without a model call (claude: `claude auth status`);
 * null when unknown.
 */
auth: AgentAuth | null, 
/**
 * Headless login token (claude only, §7); null for other agents. The
 * token itself is never sent.
 */
token: AgentToken | null, };

/**
 * How blirp memory reaches an agent (§9).
 */
export type AgentIntegration = { 
/**
 * Opt-in global hooks in the agent's user config (sessions started outside blirp).
 */
global_hooks: IntegrationState, 
/**
 * blirp MCP server registered in the agent's user config.
 */
mcp: IntegrationState, 
/**
 * Session-start injection used when the session is launched from blirp.
 */
inject: InjectMode, 
/**
 * Extra information, e.g. a manual step the agent requires.
 */
detail: string | null, };

/**
 * Login state of an agent CLI as seen by the daemon's own process (on
 * macOS a daemon started over SSH cannot read the login keychain, so it
 * may differ from a terminal on the same machine).
 */
export type AgentAuth = { logged_in: boolean, 
/**
 * How it is logged in, as the agent reports it (e.g. `claude.ai`, `api_key`).
 */
method: string | null, };

/**
 * Whether claude sessions and the summarizer on this machine log in with a
 * long-lived OAuth token (`claude setup-token`) instead of the keychain or
 * `~/.claude/.credentials.json`, which a daemon started by launchd on a
 * locked Mac or over SSH cannot use.
 */
export type AgentToken = { 
/**
 * A token is stored in `BLIRP_HOME/secrets/claude_oauth_token`
 * (`blirp agents set-token claude`).
 */
stored: boolean, 
/**
 * The daemon's own environment already sets `CLAUDE_CODE_OAUTH_TOKEN`;
 * sessions inherit it and a stored token is not used.
 */
env: boolean, };

/**
 * `PUT /api/agents/claude/token` (admin).
 */
export type SetAgentToken = { token: string, };

/**
 * `GET /api/machines/:id/dirs`: folders on a machine, for picking where a
 * session runs. Only directories are listed, never file names or contents,
 * and only inside that machine's user home.
 */
export type MachineDirs = { machine_id: string, 
/**
 * Absolute home folder the listing is confined to.
 */
home: string, 
/**
 * Absolute path of the listed folder.
 */
path: string, 
/**
 * Absolute parent folder, null at the home folder.
 */
parent: string | null, entries: Array<MachineDir>, 
/**
 * More folders exist than were returned.
 */
truncated: boolean, };

export type MachineDir = { name: string, 
/**
 * Absolute path on that machine.
 */
path: string, 
/**
 * Contains a `.git` entry.
 */
is_git: boolean, };

/**
 * `POST /api/machines/:id/clone`: clone a git repository on a machine.
 * Give `url`, or `project_id` to use the remote of that project's git folder
 * on the machine receiving the request (credentials in it are removed).
 */
export type CloneRepo = { url?: string, project_id?: string, 
/**
 * Absolute folder inside the target's home to clone into; default `~/blirp`.
 */
parent?: string, 
/**
 * Folder name; default the repository name.
 */
name?: string, };

/**
 * A clone started by `POST /api/machines/:id/clone`; poll
 * `GET /api/machines/:id/clone/:job` until it is no longer `running`.
 */
export type CloneJob = { id: string, machine_id: string, 
/**
 * The URL cloned, without credentials.
 */
url: string, 
/**
 * Absolute destination folder on that machine.
 */
dest: string, state: CloneState, 
/**
 * Last progress line from git.
 */
progress: string | null, 
/**
 * git's error output when it failed.
 */
error: string | null, started_at: number, finished_at: number | null, };

/**
 * `GET /api/inject`: the rendered memory injection.
 */
export type Injection = { markdown: string, };

export type SummaryItem = { title: string, body: string, };

/**
 * Last failed distill attempt of a session.
 */
export type DistillFailure = { message: string, at: number, 
/**
 * Highest event seq the failed attempt covered; retried only after newer events.
 */
through_seq: number, };

/**
 * Shape of `Session.summary` (the `summary_json` column, §9 distill output).
 */
export type SessionSummary = { title: string | null, 
/**
 * 3-6 sentences; null until a distill succeeded.
 */
summary: string | null, decisions: Array<SummaryItem>, open_threads: Array<SummaryItem>, gotchas: Array<SummaryItem>, resolved_record_ids: Array<string>, 
/**
 * Files touched, relative to the session folder.
 */
files: Array<string>, 
/**
 * Summarizer backend that produced it (`claude`, `codex`, `ollama`).
 */
backend: string | null, distilled_at: number | null, through_seq: number, 
/**
 * Set when the last distill attempt failed.
 */
error: DistillFailure | null, };

export type SettingsView = { config: Config, 
/**
 * UI preferences and other free-form values stored in the database.
 */
values: { [key in string]: JsonValue }, 
/**
 * Automatic distilling (§9): paused summarizer, today's budget.
 */
distill: DistillStatus, };

export type SettingsPatch = { 
/**
 * The edited config, validated and written to `config.toml`.
 * `daemon.port` takes effect after a daemon restart. `sync.role` and
 * `sync.hub` are never taken from it: hub enable/disable, join and
 * leave own them.
 */
config?: Config, 
/**
 * The config `config` was edited from (as read from `GET /api/settings`).
 * With it only the values the client changed are applied, so a stale
 * copy never reverts what changed since; without it `config` replaces
 * every other value.
 */
base?: Config, 
/**
 * Keys to set; a null value deletes the key.
 */
values?: { [key in string]: JsonValue | null }, };

/**
 * Rights of the calling client (§11), so a UI can hide what the daemon
 * would refuse.
 */
export type Capabilities = { 
/**
 * Configuration, sync, devices, agent integration, invites, open,
 * shutdown: local clients (runtime token) only.
 */
admin: boolean, 
/**
 * Launch/resume/stop sessions, type into terminals, change memory:
 * local clients, browser devices allowed to control terminals, and
 * requests relayed from a machine allowed to.
 */
control_terminals: boolean, 
/**
 * The client authenticated with this machine's runtime token.
 */
local: boolean, };

export type DistillStatus = { 
/**
 * Set while automatic distilling is paused.
 */
paused: DistillPause | null, 
/**
 * The summarizer's last error while paused.
 */
reason: string | null, 
/**
 * When the summarizer is tried again (unix ms).
 */
retry_at: number | null, 
/**
 * Distill jobs run today (UTC) and the daily limit.
 */
budget_used: number, budget_limit: number, };

/**
 * Why automatic distilling is paused: the summarizer itself fails, not a
 * session (§9). Retried with exponential backoff.
 */
export type DistillPause = "auth" | "unavailable" | "rate_limited";

/**
 * What `memory.summarizer = "auto"` resolves to on this machine right now
 * (`GET /api/settings/summarizer`, §9).
 */
export type SummarizerPick = { 
/**
 * `claude`, `codex` or `ollama`; null when none is available.
 */
backend: Summarizer | null, 
/**
 * Model it runs (`sonnet`, the Ollama model); null for codex, which
 * uses its built-in default.
 */
model: string | null, 
/**
 * `agents.default`, the agent preselected for new sessions.
 */
default_agent: string, 
/**
 * Why the default agent's own summarizer is not used; null when it is.
 */
fallback: SummarizerFallback | null, };

export type SummarizerFallback = "no_backend" | "not_installed" | "not_logged_in" | "outdated";

/**
 * `GET /api/sync/status` (§10).
 */
export type SyncStatus = { role: MachineRole, 
/**
 * This machine's id (its iroh endpoint id).
 */
machine_id: string, 
/**
 * Hub endpoint id: the paired hub on a node, this machine on a hub,
 * null when standalone.
 */
hub: string | null, 
/**
 * Node: the sync session with the hub is up. Hub: the endpoint is running.
 */
connected: boolean, 
/**
 * Last completed exchange with the hub (node) or with any node (hub).
 */
last_sync_at: number | null, 
/**
 * Local writes not yet acknowledged by the hub (0 on a hub or standalone).
 */
pending_outbox: number, 
/**
 * HTTPS LAN portal (hub with `portal.lan`), null when not serving.
 */
portal_url: string | null, 
/**
 * SHA-256 of the portal's self-signed certificate, `AA:BB:...`.
 */
portal_cert_fingerprint: string | null, 
/**
 * Relay server the sync endpoint is connected to (its home relay), so
 * machines behind other networks can reach it. Null when relays are
 * off, no endpoint runs, or no relay has answered yet.
 */
relay_url: string | null, };

/**
 * `POST /api/sync/invite`: show `code` and `invite` (or a QR of `uri`) to
 * the machine that joins.
 */
export type SyncInvite = { 
/**
 * `blirp1-<base32 ticket>`
 */
invite: string, 
/**
 * `XXXX-XXXX`, single use, 5 attempts.
 */
code: string, 
/**
 * `blirp://join/<invite>#<code>`
 */
uri: string, expires_at: number, };

/**
 * `POST /api/sync/join`.
 */
export type JoinHub = { 
/**
 * Invite from the hub; an empty string finds the hub on the local network.
 */
invite: string, code: string, 
/**
 * Sets `sync.allow_hub_control` together with the pairing; left out,
 * the configured value stays (off by default).
 */
allow_hub_control?: boolean, };

/**
 * `POST /api/sync/join/preview`: what an invite says about its hub,
 * without contacting it.
 */
export type JoinPreviewRequest = { 
/**
 * Invite or `blirp://join/...` link; empty for a LAN join by code.
 */
invite: string, };

export type JoinPreview = { 
/**
 * The hub's machine id (its endpoint id, verified by the connection
 * when pairing); null when the hub is found on the LAN by code alone.
 */
hub_id: string | null, };

/**
 * `POST /api/sync/leave`: this machine is standalone again.
 */
export type LeftHub = { status: SyncStatus, 
/**
 * Set when the hub could not be told (it still lists this machine as
 * paired) or changes made here had not reached it.
 */
warning: string | null, };

/**
 * `POST /api/ws-ticket` (loopback listener): browsers cannot send
 * `Authorization` on a WebSocket, so they trade the bearer token for a
 * single-use ticket bound to one path and pass it as `?ticket=`.
 */
export type WsTicketRequest = { 
/**
 * WebSocket path, e.g. `/api/events/ws`.
 */
path: string, };

export type WsTicket = { 
/**
 * Valid for 30 s, once, for the requested path only.
 */
ticket: string, };

/**
 * `POST /api/devices/browser-invite`: one-time login link for a browser (5 min).
 */
export type BrowserInvite = { url: string, expires_at: number, };

/**
 * `PATCH /api/devices/:id`.
 */
export type PatchDevice = { can_control_terminals: boolean, };

/**
 * Frames pushed on `/api/events/ws`.
 */
export type ServerEvent = { "type": "session_created", session: Session, } | { "type": "session_updated", session: Session, } | { "type": "session_deleted", session_id: string, } | { "type": "project_updated", project_id: string, } | { "type": "memory_updated", project_id: string, part: MemoryPart, } | { "type": "sync_updated", status: SyncStatus, } | { "type": "files_updated" } | { "type": "resync" };

/**
 * Text frames sent by the server on `/api/terminals/:id/ws` (§6). Raw
 * terminal output is sent as binary frames.
 */
export type TerminalServerMessage = { "type": "snapshot", cols: number, rows: number, data: string, } | { "type": "readonly" } | { "type": "resize", cols: number, rows: number, } | { "type": "exit", status: SessionStatus, exit_code: number | null, };

/**
 * Text frames accepted from clients on `/api/terminals/:id/ws`. Binary frames
 * are written to the terminal as raw input bytes.
 */
export type TerminalClientMessage = { "type": "input", data: string, } | { "type": "resize", cols: number, rows: number, };

/**
 * User configuration. Every section and key is optional; missing values take defaults.
 */
export type Config = { daemon: DaemonConfig, machine: MachineConfig, agents: AgentsConfig, sessions: SessionsConfig, memory: MemoryConfig, sync: SyncConfig, portal: PortalConfig, update: UpdateConfig, files: FilesConfig, };

export type DaemonConfig = { 
/**
 * Local API port on 127.0.0.1. The daemon refuses to start when it is
 * taken (another program could otherwise answer at the well-known
 * address); `0` explicitly picks a free port each start.
 */
port: number, };

export type MachineConfig = { name: string, };

export type AgentsConfig = { 
/**
 * Agent preselected in the new-session dialog: a built-in id or `custom:<name>`.
 */
default: string, custom: Array<CustomAgent>, };

export type CustomAgent = { name: string, command: string, args: Array<string>, };

export type SessionsConfig = { worktree_default: boolean, 
/**
 * Keep this machine from sleeping while any session it runs is live.
 * Unset: on for the hub role (cloud sessions), off otherwise.
 */
keep_awake?: boolean, };

/**
 * State of the last scan of a folder: `busy` while a git operation
 * holds the index, `too_large` over the caps (paused until a
 * `.blirpignore` shrinks it).
 */
export type FilesScanState = "ok" | "busy" | "too_large";

/**
 * Excluded paths of one reason: how many, and the first 50 (folders end
 * with `/`).
 */
export type ExcludedGroup = { reason: Reason, count: number, paths: Array<string>, };

/**
 * `GET /api/projects/:id/files-sync/preview?root=`: what uploading this
 * folder would send, computed locally (a dry run: nothing leaves the
 * machine).
 */
export type FilesPreview = { root: string, state: FilesScanState, 
/**
 * Why this folder is never synced (Home, scratch, removable drive...),
 * null when it can be.
 */
never_synced: string | null, files: number, bytes: number, excluded: Array<ExcludedGroup>, 
/**
 * Secrets that `.blirpignore` re-includes: they are uploaded.
 */
reincluded_secrets: Array<string>, };

/**
 * Why a path is not synced.
 */
export type Reason = "ignored" | "secret" | "too_large" | "unsupported";

/**
 * Per-project file sync setting, stored on the hub (`file_projects`).
 */
export type FilesMode = "default" | "on" | "off";

/**
 * A root on the hub with its totals.
 */
export type RootInfo = { root_id: string, project_id: string, 
/**
 * Origin machine and folder.
 */
machine_id: string, machine_name: string, 
/**
 * The origin machine was revoked: nothing uploads to this root anymore.
 */
origin_revoked: boolean, path: string, 
/**
 * Newest version (the root's sequence).
 */
head: number, files: number, bytes: number, 
/**
 * Live conflict copies (`*.conflict-*`).
 */
conflicts: number, created_at: number, updated_at: number, manifest: GitManifest | null, };

/**
 * Git facts of a root, read with plain git commands on its origin and
 * sent with every commit batch. A copy elsewhere clones `remote` and
 * checks out `head_sha` (else `branch`) before the hub's files are written
 * on top.
 */
export type GitManifest = { 
/**
 * Remote URL without credentials.
 */
remote: string | null, branch: string | null, head_sha: string | null, upstream_sha: string | null, };

/**
 * What the file engine is doing with one folder here: `waiting` for
 * the first-run grace period or the hub, `off` when the project's file
 * sync is off, `paused` by "Pause file sync", `never_synced` for
 * folders that never sync (see the message).
 */
export type CopyState = "waiting" | "scanning" | "idle" | "uploading" | "paused" | "off" | "too_large" | "busy" | "error" | "never_synced";

/**
 * This machine's working copy of a root: its own folder (the origin,
 * upload-only in v1) or a copy downloaded from the hub.
 */
export type LocalFiles = { path: string, origin: boolean, state: CopyState, 
/**
 * Why it is in that state (error, never-synced reason).
 */
message: string | null, last_upload_at: number | null, files: number, bytes: number, 
/**
 * Changes not on the hub yet.
 */
pending: number, excluded: Array<ExcludedGroup>, reincluded_secrets: Array<string>, };

/**
 * One folder of a project that syncs (or could sync) through the hub.
 */
export type FilesRoot = { root_id: string, 
/**
 * Origin machine and folder.
 */
machine_id: string, machine_name: string, path: string, origin_revoked: boolean, 
/**
 * The hub's copy; null until the first upload.
 */
hub: RootInfo | null, 
/**
 * This machine's copy; null when it has none.
 */
local: LocalFiles | null, };

/**
 * `GET /api/projects/:id/files-sync`.
 */
export type ProjectFiles = { 
/**
 * File sync can run here (hub or node role; the hub speaks it).
 */
available: boolean, mode: FilesMode, 
/**
 * This machine's `[sync] project_files`.
 */
global: boolean, 
/**
 * Uploads run for this project's folders here.
 */
effective: boolean, 
/**
 * "Pause file sync" is on here.
 */
paused: boolean, hub_error: string | null, roots: Array<FilesRoot>, };

/**
 * `PUT /api/projects/:id/files-sync`.
 */
export type SetFilesMode = { mode: FilesMode, };

/**
 * `GET /api/files/status`: the first-run banner and the pause switch.
 */
export type FilesOverview = { available: boolean, enabled: boolean, paused: boolean, 
/**
 * Uploads start then (first run after upgrade or pairing); null when
 * they already run.
 */
grace_until: number | null, hub_name: string | null, 
/**
 * Folders that will upload, and their size (known once scanned).
 */
folders: number, bytes: number, hub_error: string | null, };

/**
 * `POST /api/files/pause`.
 */
export type PauseFiles = { paused: boolean, };

export type IncomingAction = "update" | "new" | "delete" | "conflict" | "skip";

/**
 * A hub version this machine's copy has not taken.
 */
export type IncomingFile = { path: string, action: IncomingAction, by_machine_name: string, at: number, };

/**
 * `GET /api/projects/:id/files-sync/incoming?root=`.
 */
export type FilesIncoming = { root: string, files: Array<IncomingFile>, };

/**
 * `POST /api/projects/:id/files-sync/apply` ("Update from hub" on a copy,
 * "Bring changes here" on the origin folder).
 */
export type ApplyFiles = { root: string, };

export type AppliedFiles = { written: number, deleted: number, 
/**
 * Local conflict copies made next to local changes.
 */
conflicts: Array<string>, 
/**
 * Paths not held here, with why.
 */
skipped: Array<string>, failed: Array<string>, };

/**
 * `POST /api/machines/:id/files/download`: a copy of a root on that
 * machine (clone + overlay for git roots, plain files otherwise).
 */
export type DownloadFiles = { root_id: string, 
/**
 * Folder to create it in (inside home); default `~/blirp`.
 */
parent?: string, 
/**
 * Folder name; default the origin folder's name.
 */
name?: string, };

/**
 * A download started with `POST /api/machines/:id/files/download`; poll
 * `GET /api/machines/:id/files/download/:job` until it is not `running`.
 */
export type DownloadJob = { id: string, machine_id: string, root_id: string, dest: string, state: CloneState, progress: string | null, error: string | null, 
/**
 * E.g. that unpushed commits appear as local changes.
 */
note: string | null, started_at: number, finished_at: number | null, };

export type Summarizer = "auto" | "claude" | "codex" | "ollama" | "none";

export type BriefMode = "auto" | "review";

export type MemoryConfig = { summarizer: Summarizer, ollama_model: string, distill_idle_secs: number, daily_distill_limit: number, brief_mode: BriefMode, inject_max_chars: number, distill_max_chars: number, 
/**
 * Inject project memory when agents start (§9). Off: sessions start
 * without memory; MCP tools and the CLI still reach it on demand.
 */
inject: boolean, 
/**
 * Agents (`claude`, `custom:<name>`, ...) that never get memory
 * injected, even when `inject` is on.
 */
inject_disabled_agents: Array<string>, };

export type SyncConfig = { role: MachineRole, 
/**
 * Hub node id; required when `role = "node"`.
 */
hub?: string, 
/**
 * `"default"`, `"disabled"` or a relay URL.
 */
relay: string, 
/**
 * Node: let requests relayed by the hub control this machine (launch,
 * resume, stop, terminal input and other changes). Off by default:
 * the hub and other paired machines can only read.
 */
allow_hub_control: boolean, 
/**
 * Find and announce machines on the local network over mDNS (hub, node
 * and `blirp pair <code>` without an invite). Off: pairing needs the
 * invite, and peers connect through relays or the addresses they know.
 */
lan_discovery: boolean, 
/**
 * Upload project folders to the hub (hub and node roles; each project
 * can override it with On or Off, see docs/project-files.md).
 */
project_files: boolean, };

export type PortalConfig = { lan: boolean, lan_port: number, };

export type UpdateConfig = { 
/**
 * Ask GitHub once a day whether a newer release exists (`GET /api/update`).
 */
check: boolean, };

/**
 * Project file sync through the hub (docs/project-files.md).
 */
export type FilesConfig = { 
/**
 * Larger files are skipped and listed.
 */
max_file_mb: number, 
/**
 * A folder with more synced bytes than this (or more than 100 000
 * files) is paused as too large.
 */
max_root_gb: number, 
/**
 * Hub: disk space for file contents; 0 = half of the free space when
 * file sync first ran on the hub.
 */
hub_quota_gb: number, 
/**
 * Upload bandwidth limit per machine; 0 = unlimited.
 */
upload_kbps: number, 
/**
 * Hub: how long replaced versions are kept.
 */
keep_versions_days: number, };
